global.__BASE__ = __dirname + "/";

const express = require("express");
const bodyParser = require("body-parser");
const mongoose = require("mongoose");
const CONFIG = require("./config/global");
const CronJob = require('cron').CronJob;

const API_index = require("./api/index");
const API_request = require("./api/request");
const requestController = require(__BASE__ +
  "modules/controllers/requestController");
const app = express();

// connect to db with url from config
mongoose.connect(
  `mongodb://${CONFIG.DB_URL}`, {
    useNewUrlParser: true,
    useCreateIndex: true,
    useFindAndModify: false
  },
  function (err) {
    if (err) {
      console.error("Database connection failed", err);
    } else {
      console.debug("Database connection successful");
    }
  }
);

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
  extended: true
}));

// using the build generated by angular as static files directory
app.use(express.static("docsAppUi"));

app.use("/api", API_index);
app.use("/api/request", API_request);

// serving index.html created by angular for all requests other than api requests.
app.get("/*", (req, res) => {
  res.sendFile('index.html', {
    root: global.__BASE__ + "docsAppUi/"
  })
})

app.listen(CONFIG.PORT, function () {
  console.log("Server listening on port " + CONFIG.PORT);
});

// Running a cronjob after every minute which completes the requests accepted five minutes ago
new CronJob('0 */1 * * * *', requestController.completeOngoingRequests, null, true);